DROP TABLE REPLY;
DROP TABLE BOARD;
DROP TABLE NEWS_ATTACH;
DROP TABLE NEWS;
DROP TABLE NOTICE;
DROP TABLE ANSWER;
DROP TABLE ITEM;
DROP TABLE QUESTION;
DROP TABLE SUBJECT;
DROP TABLE ATT_CATEGORY;
DROP TABLE CATEGORY;
DROP TABLE MEMBER;
DROP VIEW AREA;

DROP SEQUENCE REPLY_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE NEWS_SEQ;