DROP TABLE REPLY;
DROP TABLE BRD_ATTACH;
DROP TABLE BOARD;
DROP TABLE NEWS_ATTACH;
DROP TABLE NEWS;
DROP TABLE NOTICE;
DROP TABLE ANSWER;
DROP TABLE ITEM;
DROP TABLE QUESTION;
DROP TABLE SUBJECT;
DROP TABLE ATT_CATEGORY;
DROP TABLE CATEGORY;
DROP TABLE APPLY;
DROP TABLE MEMBER_AUTH;
DROP TABLE PERSISTENT_LOGINS;

DROP VIEW AREA;
DROP VIEW STATS_TABLE;
DROP VIEW V_RESEARCH;
DROP TABLE MEMBER;

DROP SEQUENCE REPLY_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE NEWS_SEQ;
DROP SEQUENCE APPLY_SEQ;